language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run test:ci
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: form-builder-js.surge.sh
  project: ./deploy/
on:
  branch: master
